# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://coldwoong-moon.github.io/"
languageCode = "ko"
defaultContentLanguage = "ko"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  # Ensure sitemap is emitted for the home page
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
