name: Add Missing Thumbnails

on:
  push:
    branches: [ main ]
    paths:
      - 'content/posts/**/index.md'
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

permissions:
  contents: write  # Allow the action to push changes
  pages: write     # Allow pages deployment
  id-token: write  # Allow OIDC token generation

jobs:
  add-thumbnails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pillow pyyaml

    - name: Find posts without thumbnails and add them
      id: add-thumbnails
      run: |
        python3 << 'EOF'
        import os
        import requests
        import random
        import re
        import yaml
        from pathlib import Path
        import json

        # Unsplash API configuration
        UNSPLASH_ACCESS_KEY = "${{ secrets.UNSPLASH_ACCESS_KEY }}"
        if not UNSPLASH_ACCESS_KEY:
            print("⚠️  Warning: UNSPLASH_ACCESS_KEY not set. Using fallback method.")
            # Use Lorem Picsum for random images if Unsplash key not available
            USE_LOREM_PICSUM = True
        else:
            USE_LOREM_PICSUM = False

        # Content-based keyword mapping
        CONTENT_KEYWORDS = {
            # Programming and technology
            "binaryformatter": ["binary code", "serialization", "data security", "programming"],
            ".net": ["dotnet programming", "microsoft technology", "coding"],
            "c#": ["csharp programming", "visual studio", "coding"],
            "serialization": ["data serialization", "binary data", "data format"],
            "security": ["cybersecurity", "data protection", "security lock"],
            "legacy": ["vintage technology", "old computer", "retro tech"],
            
            # Web development
            "github": ["github logo", "version control", "git", "coding collaboration"],
            "hugo": ["static site generator", "web development", "golang"],
            "blog": ["blogging", "writing", "content creation", "laptop writing"],
            "markdown": ["markdown editor", "text editor", "writing"],
            "pages": ["web pages", "website", "web development"],
            
            # General categories
            "tutorial": ["learning", "education", "guide book"],
            "guide": ["guidebook", "instructions", "how-to"],
            "problem": ["problem solving", "solution", "puzzle"],
            "solution": ["solution", "answer", "lightbulb"],
        }

        # Fallback categories
        FALLBACK_CATEGORIES = [
            "abstract technology", "modern workspace", "programming", 
            "digital art", "minimalist", "gradient background"
        ]

        def extract_keywords_from_content(content):
            """Extract relevant keywords from post content"""
            keywords = []
            
            # Parse YAML front matter
            if content.startswith('---'):
                try:
                    fm_end = content.find('---', 3)
                    if fm_end > 0:
                        front_matter = yaml.safe_load(content[3:fm_end])
                        
                        # Extract from title
                        if 'title' in front_matter:
                            title = front_matter['title'].lower()
                            keywords.extend(title.split())
                        
                        # Extract from tags
                        if 'tags' in front_matter and isinstance(front_matter['tags'], list):
                            keywords.extend([tag.lower() for tag in front_matter['tags']])
                        
                        # Extract from categories
                        if 'categories' in front_matter and isinstance(front_matter['categories'], list):
                            keywords.extend([cat.lower() for cat in front_matter['categories']])
                except:
                    pass
            
            # Extract from content body (first 500 chars)
            content_body = content[content.find('---', 3) + 3:] if content.startswith('---') else content
            content_preview = content_body[:500].lower()
            
            # Look for technology terms
            tech_terms = ['api', 'database', 'server', 'client', 'framework', 'library', 
                         'algorithm', 'data structure', 'deployment', 'docker', 'kubernetes']
            for term in tech_terms:
                if term in content_preview:
                    keywords.append(term)
            
            return keywords

        def get_search_query_from_keywords(keywords):
            """Generate search query from extracted keywords"""
            matched_queries = []
            
            # Check against known keyword mappings
            for keyword in keywords:
                for key, queries in CONTENT_KEYWORDS.items():
                    if key in keyword:
                        matched_queries.extend(queries)
            
            if matched_queries:
                # Use the most relevant query
                return matched_queries[0]
            else:
                # Use fallback
                return random.choice(FALLBACK_CATEGORIES)

        def download_image(url, filepath):
            """Download image from URL"""
            response = requests.get(url, stream=True)
            response.raise_for_status()
            
            with open(filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            return True

        def get_random_unsplash_image(query):
            """Get random image from Unsplash with 4:3 aspect ratio"""
            url = "https://api.unsplash.com/photos/random"
            params = {
                "query": query,
                "orientation": "landscape",
                "client_id": UNSPLASH_ACCESS_KEY,
                "w": 1200,
                "h": 900  # 4:3 aspect ratio
            }
            
            response = requests.get(url, params=params)
            if response.status_code == 200:
                data = response.json()
                # Get URL with specific dimensions for 4:3 ratio
                image_url = data["urls"]["raw"] + "&w=1200&h=900&fit=crop"
                return image_url, data["user"]["name"], data["links"]["html"]
            return None, None, None

        def get_lorem_picsum_image():
            """Get random image from Lorem Picsum with 4:3 aspect ratio"""
            # Get random image with 4:3 aspect ratio
            url = "https://picsum.photos/1200/900"
            return url, "Lorem Picsum", "https://picsum.photos"

        # Find all post directories
        posts_dir = Path("content/posts")
        posts_updated = []

        for post_dir in posts_dir.iterdir():
            if not post_dir.is_dir():
                continue
            
            # Check if thumbnail or feature image already exists
            has_thumbnail = any(
                (f.name.startswith("thumbnail-") or f.name.startswith("feature-")) and 
                f.suffix in [".jpg", ".png", ".webp"]
                for f in post_dir.iterdir()
            )
            
            if has_thumbnail:
                print(f"✓ {post_dir.name} already has a thumbnail")
                continue
            
            print(f"📸 Adding thumbnail for: {post_dir.name}")
            
            # Read post content to determine appropriate image
            index_path = post_dir / "index.md"
            search_query = random.choice(FALLBACK_CATEGORIES)
            
            if index_path.exists():
                try:
                    with open(index_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    
                    # Extract keywords and determine search query
                    keywords = extract_keywords_from_content(content)
                    search_query = get_search_query_from_keywords(keywords)
                    print(f"  🔍 Using search query: {search_query}")
                except Exception as e:
                    print(f"  ⚠️  Error reading content: {e}")
            
            # Get image
            if USE_LOREM_PICSUM:
                image_url, photographer, source_url = get_lorem_picsum_image()
            else:
                image_url, photographer, source_url = get_random_unsplash_image(search_query)
                
                if not image_url:
                    # Fallback to Lorem Picsum
                    image_url, photographer, source_url = get_lorem_picsum_image()
            
            if image_url:
                # Download image as thumbnail image
                # Clean up the search query for filename
                clean_query = re.sub(r'[^a-z0-9-]', '-', search_query.lower())
                clean_query = re.sub(r'-+', '-', clean_query).strip('-')
                image_path = post_dir / f"thumbnail-{clean_query}.jpg"
                
                try:
                    download_image(image_url, image_path)
                    posts_updated.append(post_dir.name)
                    print(f"  ✅ Downloaded: {image_path.name}")
                    print(f"  📷 Credit: {photographer}")
                    
                    # Update index.md with coverAlt if needed
                    if index_path.exists():
                        with open(index_path, 'r', encoding='utf-8') as f:
                            content = f.read()
                        
                        # Check if coverAlt exists
                        if 'coverAlt:' not in content:
                            # Add coverAlt after the front matter
                            lines = content.split('\n')
                            fm_end = -1
                            fm_count = 0
                            
                            for i, line in enumerate(lines):
                                if line.strip() == '---':
                                    fm_count += 1
                                    if fm_count == 2:
                                        fm_end = i
                                        break
                            
                            if fm_end > 0:
                                # Insert before the closing ---
                                lines.insert(fm_end, f'coverAlt: "Photo by {photographer} from {source_url}"')
                                
                                with open(index_path, 'w', encoding='utf-8') as f:
                                    f.write('\n'.join(lines))
                                print(f"  ✅ Updated coverAlt in index.md")
                    
                except Exception as e:
                    print(f"  ❌ Error downloading image: {e}")

        # Summary
        print(f"\n📊 Summary: Added thumbnails to {len(posts_updated)} posts")
        if posts_updated:
            print("Posts updated:", ", ".join(posts_updated))
            
            # Create commit message
            if 'GITHUB_OUTPUT' in os.environ:
                with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                    f.write(f"posts_updated={len(posts_updated)}\n")
                    f.write(f"should_commit=true\n")
            else:
                print(f"::set-output name=posts_updated::{len(posts_updated)}")
                print(f"::set-output name=should_commit::true")
        else:
            if 'GITHUB_OUTPUT' in os.environ:
                with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                    f.write(f"should_commit=false\n")
            else:
                print(f"::set-output name=should_commit::false")
        EOF

    - name: Commit changes
      if: steps.add-thumbnails.outputs.should_commit == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add content/posts/*/thumbnail-*.jpg
        git add content/posts/*/index.md
        git commit -m "🖼️ Add missing thumbnails to ${{ steps.add-thumbnails.outputs.posts_updated }} posts"

    - name: Push changes
      if: steps.add-thumbnails.outputs.should_commit == 'true'
      run: |
        git push origin main